---
- name: Deploy GameServer DDTank
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Passo 0 - Preparar Container (Instalar Dependencias)
      ansible.builtin.pip:
        name: 
          - proxmoxer
          - requests
        state: present
        extra_args: --break-system-packages

    - name: Passo 1 - Clonar o Template (Criar a VM)
      community.general.proxmox_kvm:
        api_host: "{{ PROXMOX_HOST }}"
        api_user: "{{ PROXMOX_USER }}"
        api_token_id: "{{ PROXMOX_TOKEN_ID }}"
        api_token_secret: "{{ PROXMOX_SECRET }}"
        node: "ns1021275" 
        clone: "vm-winddtbr36" # Confirme o nome aqui
        name: "GameServer-DDTank" 
        full: yes
        storage: "data" 
        state: present
        validate_certs: no 
        timeout: 600

    - name: Passo 2 - Ligar a VM nova
      community.general.proxmox_kvm:
        api_host: "{{ PROXMOX_HOST }}"
        api_user: "{{ PROXMOX_USER }}"
        api_token_id: "{{ PROXMOX_TOKEN_ID }}"
        api_token_secret: "{{ PROXMOX_SECRET }}"
        node: "pve"
        name: "GameServer-DDTank" 
        state: started
        validate_certs: no